name = "Rexa"
author = "Lhucia"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd7cbc33d6e3020b1e6770eef8871a2a0547fe2aa0a743fd975a7a57b0015965"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
